import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import Navbar from '../components/Navbar';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="h-screen">
        <Navbar />
        <div className="p-0 md:p-40 mt-10 lg:mt-0 grid gap-3 grid-cols-1 md:grid-cols-2 my-auto">
          <div className="m-auto text-center px-20">
            <p className="text-2xl md:text-4xl font-bold text-purple-500 mb-5">
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Odit
              officiis impedit architecto ex et incidunt sequi eaque dolore at
              excepturi.
            </p>
            <Link href="/appointment">
              <button className="m-auto bg-purple-500 hover:bg-purple-400 text-white font-bold py-2 px-4 rounded">
                Book appointment
              </button>
            </Link>
          </div>
          <div className="mx-auto h-1/2 w-1/2">
            <Image
              src="/appointment.svg"
              width="100"
              height="100"
              layout="responsive"
            />
          </div>
        </div>
      </main>
    </div>
  );
}
